### ISSUE TITLE
How to change the default settings for the dgpu

### ISSUE THREAD

**Issue by abdullaayyad96** [linux-surface/surface-control#10]
Whenever I reboot, the dgpu turns off and I would have to manually switch it up again. I'm suspecting this is causing some issue with loading NVIDIA/CUDA libraries.

I'm wondering if there is an option to keep the dgpu in an 'on' status by default.

**Comment by qzed** [comment]
The default state can be controlled via module parameters of the `surface_hotplug` module. See https://github.com/linux-surface/surface-aggregator-module/wiki/Discrete-GPU#via-module-parameters for details.

**Comment by abdullaayyad96** [comment]
Thank you for your reply, apologies if my question sounds stupid but I am not sure whats the correct way of changing ubuntu module parameters permanently.

**Comment by qzed** [comment]
> apologies if my question sounds stupid

Not at all! Please feel encouraged to ask questions!

Changing module parameters should be the same on all distributions (at least as far as I know). You just need to create a `.conf` file under `/etc/modprobe.d/`, for example `/etc/modprobe.d/dgpu.conf`. With that you can set options via the format
```
options module_name option1=value1 option2=value2 ...
```
so in your case something like
```
options surface_hotplug dgpu_power_init=1
```
