### ISSUE TITLE
Android x86

### ISSUE THREAD

**Issue by Sparticuz** [linux-surface/surface-control#11]
I'm trying to add surface-control to my Android x86 device, but I get no such file or directory when I try to run it on kernel 5.8 with all the patches applied. (it does exist in /bin and it's executable). Are there any dependencies I might be missing?

**Comment by qzed** [comment]
What command are you running and what version? There have been a couple of changes regarding the kernel interface, so could be the tool and patches are out of sync (the performance mode and DTX/latch interfaces have changed a while back and dGPU control has been removed with the latest update to the patches).

**Comment by Sparticuz** [comment]
I was just trying to run -h to see if it worked. I'm building a kernel package for Android x86 for Surface devices. (I own surface 3, so I don't even need most of the utilities/iptsd). I'm applied all the patches on top of 5.8, and everything looks good. Checking surface-control was really just a first step towards getting iptsd working. I will have to write a service file because android doesn't use systemd.

**Comment by qzed** [comment]
Hmm, `-h` should work in every case. Hard dependencies are only glibc, if compiled for Linux (everything else is compiled in statically). If you haven't compiled it yourself, you might need to do that for Android (AFAIK that doesn't have a glibc). What's the full error message? Have you tried running it with the full path?

**Comment by Sparticuz** [comment]
```
/system/bin # ls | grep surface
surface
surfaceflinger
/system/bin # surface
sh: /bin/surface: No such file or directory
/system/bin # ./surface
sh: ./surface: No such file or directory
/system/bin # sh ./surface
./surface[1]: ELF: inaccessible or not found
./surface[2]: @@@@0ppp��: inaccessible or not found
./surface[3]: ��: inaccessible or not found
./surface[5]: �: inaccessible or not found
./surface[5]: �*�N0Q: inaccessible or not found
./surface[5]: �*�: inaccessible or not found
./surface[7]: : inaccessible or not found
./surface[7]: �*: inaccessible or not found
./surface[7]: �: inaccessible or not found
./surface[7]: �*�N�N/lib64/ld-linux-x86-64.so.2GNU: inaccessible or not found
./surface[7]: �: inaccessible or not found
./surface: no closing quote
```

**Comment by qzed** [comment]
I think the `No such file or directory` message in this case indicates that one of the dependencies is missing. Checking dependencies with `readelf -a surface | grep so` shows:
- `ld-linux-x86-64.so.2`
- `libpthread.so.0`
- `libgcc_s.so.1`
- `libc.so.6`

Again, I have pretty much no idea how the Android user-space differs from Linux, e.g. could be they're using a different `libc`, don't ship with `libptrhead`, or something like this. You _probably_ have to compile it yourself for the `x86_64-linux-android` target ([here](https://blog.rust-lang.org/2016/05/13/rustup.html)'s a likely outdated blog post about cross compilation with rust, most of it seems to hold up though).

**Comment by StollD** [comment]
Android doesn't use glibc, it uses bionic. Programs that are built for one libc wont work with another, so the glibc binaries won't work.

**Comment by Sparticuz** [comment]
So is there any hope to be able to use the iptsd? That's probably the most important part, or do I just need to integrate the old_driver branch into my kernel?

**Comment by qzed** [comment]
You can probably build that via the Android NDK which includes a C compiler and linker and should also include all the necessary libraries. I don't see any reason why it shouldn't work.

**Comment by qzed** [comment]
Closing this for now. We won't provide pre-built packages for Android, but I think it should be possible to compile this for Android. Let me know if there are any specific issues preventing this.
