### ISSUE TITLE
surface dgpu set no longer working

### ISSUE THREAD

**Issue by markgeejw** [linux-surface/surface-control#13]
Hi I recently reinstalled my setup and noticed that `sudo surface dgpu get` was no longer working. (An error about file not found). 

According to the [wiki](https://github.com/linux-surface/surface-aggregator-module/wiki/Discrete-GPU) on the surface aggregator module, this is no longer supported in the latest kernels. Could I just verify that this is the case? 

Checked `/sys/devices/platform/MSHW0153:00` and noticed that there is no `dgpu_power` there. 

Edit:
Kernel: 5.9.6-arch-surface

**Comment by qzed** [comment]
Yeah, that is correct. Manually setting the dGPU power state is not possible any more, reading it (via the old interface) isn't either, You can check on the dGPU power state via `cat /sys/bus/pci/devices/<dgpu-num>/power_state` manually to make sure the runtime suspend behaves the way you intend it to, but the `surface` command currently does not do that.

**Comment by comrade-skeleton** [comment]
How does one enable the dGPU now? I don't seem to be able to enable the one in the SB2 via Linux.

**Comment by qzed** [comment]
It should be visible via lspci and automatically turned on when needed by the kernel itself. So there's no need (and no way) to enable it, it should already be there.

**Comment by qzed** [comment]
The old dGPU interface has now been replaced by a new one, which is basically a wrapper around the standard PCI sysfs attributes.
