### ISSUE TITLE
SB3 13" - Error: Failed to get current performance mode

### ISSUE THREAD

**Issue by BobCostanzo** [linux-surface/surface-control#15]
Fresh install of the latest surface kernel and surface-control (via the [AUR](http://aur.archlinux.org/packages/surface-control-git)). 

Typing the following command yields the subsequent response:

```
**sudo surface performance set 2**
Error: Failed to get current performance mode

Caused by:
    0: Could not access device "/sys/bus/surface_aggregator/devices/01:03:01:00:01/perf_mode"
    1: No such file or directory (os error 2)
```
It may be simply the SB3 is unsupported, but I am unsure how to control dGPU otherwise. Similarly, dtx functions are not working.

**Comment by qzed** [comment]
What's the output of `uname -r`? I assume you're running a v5.12 kernel. With that version, the performance mode interface has been replaced by the ACPI platform profile interface. So you should run `sudo surface profile set battery-saver` or something like that.

**Comment by qzed** [comment]
Closing this due inactivity. As far as I can tell this works with the latest kernels.

**Comment by CameronSWilliamson** [comment]
I'm having the same issue on a surface book 2. I ran `uname -r` and got an output of `5.14.9-surface`.
