### ISSUE TITLE
Device '01:03:01:00:01' is inaccessible on SB3

### ISSUE THREAD

**Issue by rforzachamp821** [linux-surface/surface-control#18]
Hello to whoever sees this,
Whenever I want to set the performance mode for my Surface Book 3, it outputs [Could not access device "/sys/bus/surface_aggregator/devices/01:03:01:00:01/perf_mode"].
Whenever I go to the folder and try to create the perf_mode file as root, it does not allow me. How can i fix this (i am using Linux Mint by the way)?
A screenshot is attached below.
![Screenshot from 2021-12-13 16-19-01](https://user-images.githubusercontent.com/66303587/145819727-5ca5f844-658d-473f-8f51-dd2e4ec66222.png)
.

**Comment by qzed** [comment]
The `performance` command is for older kernels and has been replaced by the `profile` command on v5.13+ (as the kernel interface has changed to the generic ACPI platform profile interface). You should try `surface profile` instead. See `surface profile --help` for more details. Alternatively you can also use interfaces like the Gnome settings menu if you have the power profiles daemon installed (in the Power menu under Power Mode).

**Comment by rforzachamp821** [comment]
Ah, thank you. That worked for me.
