### ISSUE TITLE
Building is not deterministic - ordering of subcommands

### ISSUE THREAD

**Issue by Dariqq** [linux-surface/surface-control#21]
Hi, I am building from source and noticed that repeated builds are not identical.

Steps to reproduce:

Run `cargo run -- --help` twice (or more).
The order the subcommands appear in is different and seems random

This also affects the generated shell completion files which also depend on the same ordering.

Could we force an ordering of the subcommands (i.e. alphabetically by their name)?

<details><summary> 2 outputs  of ` cargo run`</summary>

```
Commands:
  dgpu     Control the discrete GPU
  profile  Control or query the current platform profile
  status   Show an overview of the current system status
  dtx      Control the latch/dtx-system on the Surface Book 2
  help     Print this message or the help of the given subcommand(s)

Commands:
  profile  Control or query the current platform profile
  status   Show an overview of the current system status
  dtx      Control the latch/dtx-system on the Surface Book 2
  dgpu     Control the discrete GPU
  help     Print this message or the help of the given subcommand(s)
```
</details>

**Comment by qzed** [comment]
Interesting, I hadn't noticed that before. That seems to be an issue with how I modularized things. Essentially, I stored the subcommands in a hashmap. Which is non-deterministic.

Fixed in 012625f1c90183c5a25c5e7f4770604a344d56b3 by sorting commands by name before adding them to the CLI.
