### ISSUE TITLE
Question: What is the best way to trigger a change in environment when entering tablet mode?

### ISSUE THREAD

**Issue by han-so1omon** [linux-surface/surface-control#4]
I would like to set up a script to change the default input mode to use a virtual keyboard when in tablet mode. Something like this attempt: https://bbs.archlinux.org/viewtopic.php?id=244648

Is there a directory or something where I can put such a script?

**Comment by qzed** [comment]
I assume your device is a Surface Book 2? In that case you have multiple options: 
- Rely on `SW_TABLET_MODE` input event and figure something out with this. That's device-agnostic and is the standard way in Linux to signal if a 2in1 device is in tablet mode or laptop mode. (Note: I've just changed that studio-mode is now also classified as tablet mode, so if you're using one of the pre-built kernels it may take some time until that change reaches those).
- Connect to the `org.surface.dtx` d-bus service provided by the surface-dtx daemon and listen for DeviceMode changes. That's specific to the SB2 though, but can also distinguish between studio- and "pure" tablet-mode.

Both of those require some scripting though. Another option that requires less scripting (but IMHO is somewhat of a hack) is via a udev rule, triggering a script on keyboard device changes.
